name: CI

on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "LICENSE"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.pull_request.title, 'ci skip')
    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build Docker Image
        run: make -C main build
      - name: Install Dev Dependencies
        run: make -C main test-env
      - name: Test Docker Image
        run: make -C main test
      - name: Publish Docker Image
        if: github.ref == 'refs/heads/main'
        run: >
          make -C main push
          DOCKERHUB_USERNAME="${{secrets.DOCKERHUB_USERNAME}}"
          DOCKERHUB_PASSWORD="${{secrets.DOCKERHUB_PASSWORD}}"