name: Build Docker Images

on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "LICENSE"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.pull_request.title, 'ci skip')
    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dev Dependencies
        run: make -C main install-test-deps
      - name: Test Docker Images
        run: make -C main test
      - name: Build Docker Images
        run: make -C main build
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: >
          echo '${{secrets.DOCKERHUB_PASSWORD}}' | docker login --username
          '${{secrets.DOCKERHUB_USERNAME}}' --password-stdin
      - name: Push Images to DockerHub
        if: github.ref == 'refs/heads/main'
        run: make -C main push